### ISSUE TITLE
is vuex-1.0.0.rc.2 incompatible with vuex-router-sync@2.0.2?

### ISSUE THREAD

**Issue by rockymontana** [vuejs/vuex-router-sync#19]
I can't install vuex-router-sync with vuex@1.0.0-rc.2 installed.

```
✗ npm list |grep vuex                                                                                                                                                       
└── vuex@1.0.0-rc.2
```

And:

```
✗ npm install --save-dev vuex-router-sync                                                                                                                                   /path/to/project
├── UNMET PEER DEPENDENCY vuex@1.0.0-rc.2
└── vuex-router-sync@2.0.2

npm WARN EPEERINVALID vuex-router-sync@2.0.2 requires a peer of vuex@>= 0.6.2 < 3 but none was installed.
```

Any ideas?

**Comment by player1537** [comment]
I believe the issue is caused by the use of prerelease tags. In particular, `1.0.0-rc.2`.

[This page](https://docs.npmjs.com/misc/semver#prerelease-tags) says that if you've installed a dependency with a prerelease tag (`1.0.0-rc.2`) then it will only consider a version "greater than" that tag if it has the same base (`1.0.0-rc`). This means that `1.0.0-rc.3 >= 1.0.0-rc.2`, but `1.0.1 >= 1.0.0-rc.2` will not hold, because `1.0.1` does not match `1.0.0-rc`.

In other words, if Vuex gets a non-rc candidate released (e.g. `1.0.1`) then installing that should make npm not complain about an invalid peer. Alternatively, if vuex-router-sync gets modified to also accept `vuex@>=1.0.0-rc.2` (so: `"vuex": ">=0.6.2 <3 || >=1.0.0-rc.2"`, I think) as a peer dependency, then it should work.

Also note that this is only a warning. So it installed everything correctly, it just believes that you've installed an incorrect version, but you can ignore it if vuex-router-sync is working correctly. 

_(Apologies if this information isn't correct. I was also just looking into this problem and saw your issue and decided to investigate it further)_

**Comment by rockymontana** [comment]
Thanks for your answer.
You're right. The package gets installed, but if I understand you correctly it's an easy fix, right?

Does anyone know if there are any other compabillity issues between the two with vuex being in 1.0.0-rc.2?

**Comment by imr092** [comment]
npm install vuex@2.0.0-rc.5 vuex-router-sync@3.0.0 vue-router@2.0.0-rc.3 --save
