### ISSUE TITLE
Route params is empty when reloading on the path 

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuejs/vuex-router-sync#50]
### Steps to Reproduce
- Create a getter named route function return state.route
- The render it on a component using mapGetters(['route'])

### What is expected
Route Params must have properties

###What happened

Route params is empty

**Comment by LinusBorg** [comment]
As always, please provide a minimal reproductionon jsfiddle or a smiliar service, or we can't work on this.

**Comment by ralphchristianeclipse** [comment]
wait ill make it

**Comment by ralphchristianeclipse** [comment]
dont know if i can do this in jsfiddle

**Comment by ralphchristianeclipse** [comment]
cause you need to refresh it

**Comment by LinusBorg** [comment]
> cause you need to refresh it

why? that is not even in your description.

**Comment by ralphchristianeclipse** [comment]
@LinusBorg Edit: https://jsfiddle.net/9curL4re/12/

Here is the jsfidde i don't know if this would work cause the reproduction step is to be on a nested route with a param for example

locahost/test/testParam
then refresh it
so the result will give route.params object in vuex-router-sync not to be empty

but the result is params object is empty

**Comment by ralphchristianeclipse** [comment]
I think you need to set this up on a simple vue environment

**Comment by LinusBorg** [comment]
I'm sorry but I can't do that.

 *You* are the one seeing the problem, so *you* should set this up in a simple vue environment and share the repository with iu.

We really like to help, but we have very limited resources. And in many, many cases, the actual problem is a mistake by the user, so we can't afford to "waste" time trying to build reproductions of *descriptions* of a problem that might simply be a user mistake.

The users have to provide a clear, minimal reproduction, so we can clone and test it immediately.
